### ISSUE TITLE
403 error - s3 permission issue?

### ISSUE THREAD

**Issue by tobinbradley** [mapbox/fontnik#5] opened 2016-03-03 17:12 UTC
Howdy,

npm is giving a 403 error on the tar file, and it appears S3 is refusing connections. This link:
https://mapbox-node-binary.s3.amazonaws.com/fontnik/v0.4.7/node-v45-win32-x64.tar.gz

Produces this:

```
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>30290732028A69D5</RequestId>
<HostId>
+HSup0SA3XPlq2PP0v5B9HepTlPyZzf2wh/GN0Tp5gA185CLcj7OSEN4bEkm/0Vbj/hat7yabCw=
</HostId>
</Error>
```

Thanks!

**Comment by mikemorris** [comment] 2016-03-03 17:37
Dupe of https://github.com/mapbox/fontmachine/issues/7 - node-fontnik does not currently support Windows (and therefore we aren't publishing Windows binaries). A pull request over in https://github.com/mapbox/node-fontnik (this repo is for a confusingly-similarly-named JavaScript-only project) adding Windows support would be welcome though!

**Closed as completed by mikemorris** 2016-03-03 17:37 UTC
